CREATE TABLE [Purchasing].[Fact_DockingAppointmentTemporalSnapshots] (
    [Docking_Appointments_sk]          INT             IDENTITY (1, 1) NOT NULL,
    [Total_Pieces]                     INT             NULL,
    [Total_Applied_Freight]            DECIMAL (9, 2)  NULL,
    [Total_Estimated_Freight]          INT             NULL,
    [Docking_Quantity]                 INT             NULL,
    [Print_Quantity]                   INT             NULL,
    [Previous_Print_Quantity]          INT             NULL,
    [Crossdock_Scheduled_Quantity]     INT             NULL,
    [Crossdock_Actual_Quantity]        INT             NULL,
    [Sold_Quantity]                    INT             NULL,
    [Max_Sellable_Quantity]            INT             NULL,
    [Merchandising_Unit_Cost]          DECIMAL (12, 2) NULL,
    [Docking_Cost]                     DECIMAL (12, 2) NULL,
    [Print_Cost]                       DECIMAL (12, 2) NULL,
    [Previous_Print_Cost]              DECIMAL (12, 2) NULL,
    [Crossdock_Scheduled_Cost]         DECIMAL (12, 2) NULL,
    [Crossdock_Actual_Cost]            DECIMAL (12, 2) NULL,
    [Sold_Cost]                        DECIMAL (12, 2) NULL,
    [Max_Sellable_Cost]                DECIMAL (12, 2) NULL,
    [Docking_Date_fk]                  INT             NOT NULL,
    [Guaranteed_Date_fk]               INT             NOT NULL,
    [Quick_Ship_Order_Date_fk]         INT             NOT NULL,
    [Received_Date_fk]                 INT             NOT NULL,
    [Docking_Create_Date_fk]           INT             NOT NULL,
    [Location_fk]                      INT             NOT NULL,
    [SKU_fk]                           INT             NOT NULL,
    [SKU_History_fk]                   INT             NOT NULL,
    [Shipper_fk]                       INT             NOT NULL,
    [Shipping_Origin_fk]               INT             NOT NULL,
    [Transaction_Link_fk]              INT             NOT NULL,
    [Docking_Number_nk]                INT             NULL,
    [Division_nk]                      INT             NULL,
    [Market_nk]                        INT             NULL,
    [PO_Number_nk]                     VARCHAR (50)    NULL,
    [PO_Line_Number_nk]                INT             NULL,
    [Receive_Sequence_Number_nk]       INT             NULL,
    [Master_PO_Number_nk]              VARCHAR (50)    NULL,
    [Docking_Status_Code]              VARCHAR (2)     NULL,
    [Docking_Status]                   VARCHAR (50)    NULL,
    [Warehouse_To_Store_Transfer_Flag] VARCHAR (50)    NULL,
    [Intracompany_Transfer_Flag]       VARCHAR (50)    NULL,
    [Header_Type]                      VARCHAR (4)     NULL,
    [Confirmed_Header_Flag]            VARCHAR (1)     NULL,
    [Reviewed_Flag]                    VARCHAR (1)     NULL,
    [Quick_Ship_Auto_Create_Flag]      VARCHAR (1)     NULL,
    [Show_as_Paid_Flag]                VARCHAR (1)     NULL,
    [Container]                        VARCHAR (11)    NULL,
    [Container_Flag]                   VARCHAR (1)     NULL,
    [Freight_Type_Code]                VARCHAR (1)     NULL,
    [Freight_Type]                     VARCHAR (50)    NULL,
    [Origination_Type_Code]            VARCHAR (1)     NULL,
    [Origination_Type]                 VARCHAR (50)    NULL,
    [Shipment_Type_Code]               VARCHAR (3)     NULL,
    [Shipment_Type]                    VARCHAR (50)    NULL,
    [Cube_Rate]                        INT             NULL,
    [Shipment_Number]                  INT             NULL,
    [Confirmed_Detail_Flag]            VARCHAR (1)     NULL,
    [Ok_to_Sell_Against_Flag]          VARCHAR (1)     NULL,
    [Key_Hash]                         CHAR (64)       NOT NULL,
    [Row_Value_Hash]                   CHAR (64)       NOT NULL,
    [Snapshot_StartDate]               DATE            NOT NULL,
    [Snapshot_EndDate]                 DATE            NOT NULL,
    [Snapshot_Current_Flag]            BIT             NOT NULL,
    [SourceSystem_fk]                  INT             NOT NULL,
    [ETLBatchID_Insert]                INT             NOT NULL,
    [ETLBatchID_Update]                INT             NOT NULL,
    CONSTRAINT [PK_Docking_Appointments_sk] PRIMARY KEY NONCLUSTERED ([Docking_Appointments_sk] ASC),
    CONSTRAINT [FK_Fact_DockingAppointmentTemporalSnapshots_Dim_Date_Docking] FOREIGN KEY ([Docking_Date_fk]) REFERENCES [DW].[Dim_Date] ([Date_sk]),
    CONSTRAINT [FK_Fact_DockingAppointmentTemporalSnapshots_Dim_Date_Docking_Create] FOREIGN KEY ([Docking_Create_Date_fk]) REFERENCES [DW].[Dim_Date] ([Date_sk]),
    CONSTRAINT [FK_Fact_DockingAppointmentTemporalSnapshots_Dim_Date_Guaranteed] FOREIGN KEY ([Guaranteed_Date_fk]) REFERENCES [DW].[Dim_Date] ([Date_sk]),
    CONSTRAINT [FK_Fact_DockingAppointmentTemporalSnapshots_Dim_Date_Quick_Ship_Order] FOREIGN KEY ([Quick_Ship_Order_Date_fk]) REFERENCES [DW].[Dim_Date] ([Date_sk]),
    CONSTRAINT [FK_Fact_DockingAppointmentTemporalSnapshots_Dim_Date_Received] FOREIGN KEY ([Received_Date_fk]) REFERENCES [DW].[Dim_Date] ([Date_sk]),
    CONSTRAINT [FK_Fact_DockingAppointmentTemporalSnapshots_Dim_Location] FOREIGN KEY ([Location_fk]) REFERENCES [DW].[Dim_Location] ([Location_sk]),
    CONSTRAINT [FK_Fact_DockingAppointmentTemporalSnapshots_Dim_Shipper] FOREIGN KEY ([Shipper_fk]) REFERENCES [DW].[Dim_Vendor] ([Vendor_sk]),
    CONSTRAINT [FK_Fact_DockingAppointmentTemporalSnapshots_Dim_ShippingOrigin] FOREIGN KEY ([Shipping_Origin_fk]) REFERENCES [DW].[Dim_ShippingOrigin] ([Shipping_Origin_sk]),
    CONSTRAINT [FK_Fact_DockingAppointmentTemporalSnapshots_Dim_SKU] FOREIGN KEY ([SKU_fk]) REFERENCES [DW].[Dim_SKU] ([SKU_sk]),
    CONSTRAINT [FK_Fact_DockingAppointmentTemporalSnapshots_Dim_SKU_History] FOREIGN KEY ([SKU_History_fk]) REFERENCES [DW].[Dim_SKU_History] ([SKU_History_sk])
);


GO
CREATE CLUSTERED COLUMNSTORE INDEX [Fact_DockingAppointmentTemporalSnapshots]
    ON [Purchasing].[Fact_DockingAppointmentTemporalSnapshots];

