CREATE TABLE [Purchasing].[Fact_ShipmentsTemporalSnapshots] (
    [Shipments_sk]                           INT             IDENTITY (1, 1) NOT NULL,
    [Carton_Quantity]                        INT             NULL,
    [Shipment_Weight_KG]                     DECIMAL (10, 2) NULL,
    [Shipment_Weight_LBS]                    DECIMAL (10, 2) NULL,
    [Volume_Cubic_Feet]                      DECIMAL (8, 2)  NULL,
    [Docking_Total_Pieces]                   INT             NULL,
    [Docking_Total_Applied_Freight]          DECIMAL (9, 2)  NULL,
    [Docking_Total_Estimated_Freight]        INT             NULL,
    [Docking_Date_fk]                        INT             NOT NULL,
    [Guaranteed_Date_fk]                     INT             NOT NULL,
    [Quick_Ship_Order_Date_fk]               INT             NOT NULL,
    [Estimated_Ship_Date_fk]                 INT             NOT NULL,
    [Port_of_Origin_Departure_Date_fk]       INT             NOT NULL,
    [Arrival_at_US_Port_Date_fk]             INT             NOT NULL,
    [Arrival_at_Depot_Date_fk]               INT             NOT NULL,
    [Arrival_at_DC_Date_fk]                  INT             NOT NULL,
    [Shipment_Created_Date_fk]               INT             NOT NULL,
    [Port_of_Load_Shipping_Location_fk]      INT             NOT NULL,
    [Port_of_Discharge_Shipping_Location_fk] INT             NOT NULL,
    [Port_of_Arrival_Shipping_Location_fk]   INT             NOT NULL,
    [Shipper_fk]                             INT             NOT NULL,
    [Shipping_Origin_fk]                     INT             NOT NULL,
    [Transaction_Link_fk]                    INT             NOT NULL,
    [Shipment_Number_nk]                     INT             NULL,
    [Shipment_Sequence_Number_nk]            INT             NULL,
    [Division_nk]                            INT             NULL,
    [Market_nk]                              INT             NULL,
    [Docking_Number_nk]                      INT             NULL,
    [Vessel_Name]                            VARCHAR (30)    NULL,
    [Vessel_Number]                          VARCHAR (30)    NULL,
    [Seal_Number]                            VARCHAR (15)    NULL,
    [Carrier]                                VARCHAR (40)    NULL,
    [HashKey]                                CHAR (40)       NOT NULL,
    [Snapshot_StartDate]                     DATE            NOT NULL,
    [Snapshot_EndDate]                       DATE            NOT NULL,
    [Snapshot_Current_Flag]                  BIT             NOT NULL,
    [SourceSystem_fk]                        INT             NOT NULL,
    [ETLBatchID_Insert]                      INT             NOT NULL,
    [ETLBatchID_Update]                      INT             NOT NULL,
    CONSTRAINT [PK_Shipments_sk] PRIMARY KEY NONCLUSTERED ([Shipments_sk] ASC),
    CONSTRAINT [FK_Fact_ShipmentsTemporalSnapshots_Dim_Date_Arrival_at_DC] FOREIGN KEY ([Arrival_at_DC_Date_fk]) REFERENCES [DW].[Dim_Date] ([Date_sk]),
    CONSTRAINT [FK_Fact_ShipmentsTemporalSnapshots_Dim_Date_Arrival_at_Depot] FOREIGN KEY ([Arrival_at_Depot_Date_fk]) REFERENCES [DW].[Dim_Date] ([Date_sk]),
    CONSTRAINT [FK_Fact_ShipmentsTemporalSnapshots_Dim_Date_Arrival_at_US_Port] FOREIGN KEY ([Arrival_at_US_Port_Date_fk]) REFERENCES [DW].[Dim_Date] ([Date_sk]),
    CONSTRAINT [FK_Fact_ShipmentsTemporalSnapshots_Dim_Date_Docking] FOREIGN KEY ([Docking_Date_fk]) REFERENCES [DW].[Dim_Date] ([Date_sk]),
    CONSTRAINT [FK_Fact_ShipmentsTemporalSnapshots_Dim_Date_Estimated_Ship] FOREIGN KEY ([Estimated_Ship_Date_fk]) REFERENCES [DW].[Dim_Date] ([Date_sk]),
    CONSTRAINT [FK_Fact_ShipmentsTemporalSnapshots_Dim_Date_Guaranteed] FOREIGN KEY ([Guaranteed_Date_fk]) REFERENCES [DW].[Dim_Date] ([Date_sk]),
    CONSTRAINT [FK_Fact_ShipmentsTemporalSnapshots_Dim_Date_Port_of_Origin] FOREIGN KEY ([Port_of_Origin_Departure_Date_fk]) REFERENCES [DW].[Dim_Date] ([Date_sk]),
    CONSTRAINT [FK_Fact_ShipmentsTemporalSnapshots_Dim_Date_Quick_Ship] FOREIGN KEY ([Quick_Ship_Order_Date_fk]) REFERENCES [DW].[Dim_Date] ([Date_sk]),
    CONSTRAINT [FK_Fact_ShipmentsTemporalSnapshots_Dim_Date_Shipment_Created] FOREIGN KEY ([Shipment_Created_Date_fk]) REFERENCES [DW].[Dim_Date] ([Date_sk]),
    CONSTRAINT [FK_Fact_ShipmentsTemporalSnapshots_Dim_ShippingOrigin] FOREIGN KEY ([Shipping_Origin_fk]) REFERENCES [DW].[Dim_ShippingOrigin] ([Shipping_Origin_sk]),
    CONSTRAINT [FK_Fact_ShipmentsTemporalSnapshots_Dim_ShippingOrigin_Port_of_Arrival] FOREIGN KEY ([Port_of_Arrival_Shipping_Location_fk]) REFERENCES [DW].[Dim_ShippingOrigin] ([Shipping_Origin_sk]),
    CONSTRAINT [FK_Fact_ShipmentsTemporalSnapshots_Dim_ShippingOrigin_Port_of_Discharge] FOREIGN KEY ([Port_of_Discharge_Shipping_Location_fk]) REFERENCES [DW].[Dim_ShippingOrigin] ([Shipping_Origin_sk]),
    CONSTRAINT [FK_Fact_ShipmentsTemporalSnapshots_Dim_ShippingOrigin_Port_of_Load] FOREIGN KEY ([Port_of_Load_Shipping_Location_fk]) REFERENCES [DW].[Dim_ShippingOrigin] ([Shipping_Origin_sk]),
    CONSTRAINT [FK_Fact_ShipmentsTemporalSnapshots_Dim_Vendor_Shipper] FOREIGN KEY ([Shipper_fk]) REFERENCES [DW].[Dim_Vendor] ([Vendor_sk])
);


GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_Fact_ShipmentsTemporalSnapshots]
    ON [Purchasing].[Fact_ShipmentsTemporalSnapshots];

