CREATE TABLE [DW].[Dim_SKU_SpecialOrderAttributes] (
    [SKU_sk]                               INT           NOT NULL,
    [SKU_Unformatted_nk]                   VARCHAR (9)   NOT NULL,
    [Accent_Fabric]                        VARCHAR (255) NOT NULL,
    [Arm_Type]                             VARCHAR (255) NOT NULL,
    [Armcap]                               VARCHAR (255) NOT NULL,
    [Back_and_Seat_Cushion_Core]           VARCHAR (255) NOT NULL,
    [Back_Cushion_Attachment]              VARCHAR (255) NOT NULL,
    [Back_Cushion_Style]                   VARCHAR (255) NOT NULL,
    [Base_Type]                            VARCHAR (255) NOT NULL,
    [Body_Fabric]                          VARCHAR (255) NOT NULL,
    [Body_Fabric_#1]                       VARCHAR (255) NOT NULL,
    [Body_Fabric_#2]                       VARCHAR (255) NOT NULL,
    [Body_Fabric_#3]                       VARCHAR (255) NOT NULL,
    [Body_Fabric_Headboard_Back]           VARCHAR (255) NOT NULL,
    [Border_Location]                      VARCHAR (255) NOT NULL,
    [Bottom_Color]                         VARCHAR (255) NOT NULL,
    [Buttons]                              VARCHAR (255) NOT NULL,
    [Buttons_#1]                           VARCHAR (255) NOT NULL,
    [Buttons_#2]                           VARCHAR (255) NOT NULL,
    [Chair_Finish]                         VARCHAR (255) NOT NULL,
    [Chair_Seat_Finish]                    VARCHAR (255) NOT NULL,
    [Distressing]                          VARCHAR (255) NOT NULL,
    [Door_Hardware]                        VARCHAR (255) NOT NULL,
    [Drapery_Border]                       VARCHAR (255) NOT NULL,
    [Drapery_Heading]                      VARCHAR (255) NOT NULL,
    [Drapery_Length]                       VARCHAR (255) NOT NULL,
    [Drapery_Rod_Size]                     VARCHAR (255) NOT NULL,
    [Drawer_Hardware]                      VARCHAR (255) NOT NULL,
    [Fabrics]                              VARCHAR (255) NOT NULL,
    [Finish_Color]                         VARCHAR (255) NOT NULL,
    [Frame]                                VARCHAR (255) NOT NULL,
    [Fringe/Cord]                          VARCHAR (255) NOT NULL,
    [Fringe/Cord_#1]                       VARCHAR (255) NOT NULL,
    [Fringe/Cord_#2]                       VARCHAR (255) NOT NULL,
    [Fringe/Cord_#3]                       VARCHAR (255) NOT NULL,
    [Fringe/Cord_#4]                       VARCHAR (255) NOT NULL,
    [Fringe/Cord_Individual]               VARCHAR (255) NOT NULL,
    [Joiner]                               VARCHAR (255) NOT NULL,
    [Kidney_Pillow_-_Back]                 VARCHAR (255) NOT NULL,
    [Kidney_Pillow_-_Front]                VARCHAR (255) NOT NULL,
    [Nailhead]                             VARCHAR (255) NOT NULL,
    [Nailhead_for_Arm]                     VARCHAR (255) NOT NULL,
    [Nailhead_Spacing]                     VARCHAR (255) NOT NULL,
    [Picture_Frame_Fabric]                 VARCHAR (255) NOT NULL,
    [Pillow_Fabric-497]                    VARCHAR (255) NOT NULL,
    [Pillow_Fabric-508]                    VARCHAR (255) NOT NULL,
    [Pillow_Fabric_(Individual)]           VARCHAR (255) NOT NULL,
    [Pillow_Fabric_(Pair)]                 VARCHAR (255) NOT NULL,
    [Pillow_Fabric_#1_Individual]          VARCHAR (255) NOT NULL,
    [Pillow_Fabric_#1Pair]                 VARCHAR (255) NOT NULL,
    [Pillow_Fabric_#2_Individual]          VARCHAR (255) NOT NULL,
    [Pillow_Fabric_#2_Pair]                VARCHAR (255) NOT NULL,
    [Pillow_Fabric_#3_Individual]          VARCHAR (255) NOT NULL,
    [Pillow_Fabric_1_-_Back_(individual)]  VARCHAR (255) NOT NULL,
    [Pillow_Fabric_1_-_Back_(pair)]        VARCHAR (255) NOT NULL,
    [Pillow_Fabric_1_-_Front_(individual)] VARCHAR (255) NOT NULL,
    [Pillow_Fabric_1_-_Front_(pair)]       VARCHAR (255) NOT NULL,
    [Pillow_Fabric_2_-_Back_(individual)]  VARCHAR (255) NOT NULL,
    [Pillow_Fabric_2_-_Back_(pair)]        VARCHAR (255) NOT NULL,
    [Pillow_Fabric_2_-_Front_(individual)] VARCHAR (255) NOT NULL,
    [Pillow_Fabric_2_-_Front_(pair)]       VARCHAR (255) NOT NULL,
    [Pillow_Fabric_3_-_Back_(individual)]  VARCHAR (255) NOT NULL,
    [Pillow_Fabric_3_-_Back_(pair)]        VARCHAR (255) NOT NULL,
    [Pillow_Fabric_3_-_Front_(individual)] VARCHAR (255) NOT NULL,
    [Pillow_Fabric_3_-_Front_(pair)]       VARCHAR (255) NOT NULL,
    [Pillow_Size]                          VARCHAR (255) NOT NULL,
    [Rod_Finial]                           VARCHAR (255) NOT NULL,
    [Rug_Color_A]                          VARCHAR (255) NOT NULL,
    [Rug_Color_B]                          VARCHAR (255) NOT NULL,
    [Rug_Color_C]                          VARCHAR (255) NOT NULL,
    [Rug_Color_D]                          VARCHAR (255) NOT NULL,
    [Rug_Color_E]                          VARCHAR (255) NOT NULL,
    [Rug_Design]                           VARCHAR (255) NOT NULL,
    [Seat_Depth]                           VARCHAR (255) NOT NULL,
    [Server_Base_Finish]                   VARCHAR (255) NOT NULL,
    [Server_Top_Finish]                    VARCHAR (255) NOT NULL,
    [Solarium_Pillow_(Individual)]         VARCHAR (255) NOT NULL,
    [Solarium_Pillow_(Pair)]               VARCHAR (255) NOT NULL,
    [Stool_Height]                         VARCHAR (255) NOT NULL,
    [Sunbrella_Pillow_(Pair)]              VARCHAR (255) NOT NULL,
    [Sunbrella_Pillow_#1_Individual]       VARCHAR (255) NOT NULL,
    [Sunbrella_Pillow_#2_Individual]       VARCHAR (255) NOT NULL,
    [Table_Apron_Finish]                   VARCHAR (255) NOT NULL,
    [Table_Leg_Finish]                     VARCHAR (255) NOT NULL,
    [Table_Top_Finish]                     VARCHAR (255) NOT NULL,
    [Top_Color]                            VARCHAR (255) NOT NULL,
    [Upholstery]                           VARCHAR (255) NOT NULL,
    [Welt]                                 VARCHAR (255) NOT NULL,
    [Wing_Fabric]                          VARCHAR (255) NOT NULL,
    [7pk_Rings_with_Clips]                 VARCHAR (255) NOT NULL,
    [HashKey]                              CHAR (40)     NULL,
    [SourceSystem_fk]                      INT           NOT NULL,
    [ETLBatchID_Insert]                    INT           NOT NULL,
    [ETLBatchID_Update]                    INT           NOT NULL
);




GO
CREATE UNIQUE NONCLUSTERED INDEX [IUX_SKU_Unformatted_nk_Dim_SKU_SpecialOrderAttributes]
    ON [DW].[Dim_SKU_SpecialOrderAttributes]([SKU_Unformatted_nk] ASC) WITH (DATA_COMPRESSION = PAGE);


GO
CREATE CLUSTERED INDEX [ICX_SKU_sk_Dim_SKU_SpecialOrderAttributes]
    ON [DW].[Dim_SKU_SpecialOrderAttributes]([SKU_sk] ASC) WITH (DATA_COMPRESSION = PAGE);

