CREATE TABLE [DW].[Dim_Customer] (
    [Customer_sk]   INT            IDENTITY (1, 1) NOT NULL,
    [CustomerID]    INT            NULL,
    [NameStyle]     BIT            NULL,
    [Title]         NVARCHAR (100) NULL,
    [FirstName]     NVARCHAR (100) NULL,
    [MiddleName]    NVARCHAR (100) NULL,
    [LastName]      NVARCHAR (100) NULL,
    [Suffix]        NVARCHAR (10)  NULL,
    [FullName]      NVARCHAR (100) NULL,
    [CompanyName]   NVARCHAR (100) NULL,
    [SalesPerson]   NVARCHAR (100) NULL,
    [EmailAddress]  NVARCHAR (100) NULL,
    [Phone]         NVARCHAR (100) NULL,
    [PasswordHash]  NVARCHAR (100) NULL,
    [PasswordSalt]  NVARCHAR (100) NULL,
    [ModifiedDate]  DATETIME2 (7)  NULL,
    [AddressID]     INT            NULL,
    [AddressType]   NVARCHAR (100) NULL,
    [AddressLine1]  NVARCHAR (100) NULL,
    [AddressLine2]  NVARCHAR (100) NULL,
    [City]          NVARCHAR (100) NULL,
    [StateProvince] NVARCHAR (100) NULL,
    [CountryRegion] NVARCHAR (100) NULL,
    [PostalCode]    NVARCHAR (100) NULL
);

