CREATE TABLE [ETL].[Reconcile_Sales] (
    [Sales_Process_Number]                INT             NOT NULL,
    [Sequence]                            INT             NOT NULL,
    [Created]                             DATETIME        NOT NULL,
    [Run_Type]                            CHAR (1)        NOT NULL,
    [Extract_From_Date]                   INT             NOT NULL,
    [Extract_To_Date]                     INT             NOT NULL,
    [Row_Count_Scorecard_WRT]             INT             NULL,
    [Row_Count_SalesDB2_WRT]              INT             NULL,
    [Row_Count_SalesDW_WRT]               INT             NULL,
    [Sum_Retail_Scorecard_WRT]            DECIMAL (15, 2) NULL,
    [Sum_Retail_SalesDB2_WRT]             DECIMAL (15, 2) NULL,
    [Sum_Retail_SalesDW_WRT]              DECIMAL (15, 2) NULL,
    [Sum_TaxAmount1_SalesDB2_WRT]         DECIMAL (15, 2) NULL,
    [Sum_TaxAmount1_SalesDW_WRT]          DECIMAL (15, 2) NULL,
    [Sum_SalesUnits_SalesDB2_WRT]         INT             NULL,
    [Sum_SalesUnits_SalesDW_WRT]          INT             NULL,
    [Sum_TranNumber_Scorecard_WRT]        BIGINT          NULL,
    [Sum_TranNumber_SalesDB2_WRT]         BIGINT          NULL,
    [Sum_TranNumber_SalesDW_WRT]          BIGINT          NULL,
    [Row_Count_Scorecard_DLV]             INT             NULL,
    [Row_Count_SalesDB2_DLV]              INT             NULL,
    [Row_Count_SalesDW_DLV]               INT             NULL,
    [Sum_Retail_Scorecard_DLV]            DECIMAL (15, 2) NULL,
    [Sum_Retail_SalesDB2_DLV]             DECIMAL (15, 2) NULL,
    [Sum_Retail_SalesDW_DLV]              DECIMAL (15, 2) NULL,
    [Sum_TaxAmount1_SalesDB2_DLV]         DECIMAL (15, 2) NULL,
    [Sum_TaxAmount1_SalesDW_DLV]          DECIMAL (15, 2) NULL,
    [Sum_SalesUnits_SalesDB2_DLV]         INT             NULL,
    [Sum_SalesUnits_SalesDW_DLV]          INT             NULL,
    [Sum_TranNumber_Scorecard_DLV]        BIGINT          NULL,
    [Sum_TranNumber_SalesDB2_DLV]         BIGINT          NULL,
    [Sum_TranNumber_SalesDW_DLV]          BIGINT          NULL,
    [Seven_Days_Sum_Retail_NetSales_DLV]  DECIMAL (15, 2) NULL,
    [Seven_Days_Sum_Retail_Scorecard_DLV] DECIMAL (15, 2) NULL,
    [Seven_Days_Sum_Retail_SalesDB2_DLV]  DECIMAL (15, 2) NULL,
    [Seven_Days_Sum_Retail_SalesDW_DLV]   DECIMAL (15, 2) NULL,
    [Seven_Days_Sum_Retail_NetSales_WRT]  DECIMAL (15, 2) NULL,
    [Seven_Days_Sum_Retail_Scorecard_WRT] DECIMAL (15, 2) NULL,
    [Seven_Days_Sum_Retail_SalesDB2_WRT]  DECIMAL (15, 2) NULL,
    [Seven_Days_Sum_Retail_SalesDW_WRT]   DECIMAL (15, 2) NULL,
    CONSTRAINT [PK_Reconcile_Sales] PRIMARY KEY CLUSTERED ([Sales_Process_Number] ASC, [Sequence] ASC, [Extract_From_Date] ASC, [Extract_To_Date] ASC)
);





