CREATE TABLE [Updates].[Dim_SKU_Update] (
    [SKU_Unformatted_nk]            NVARCHAR (MAX)   NOT NULL,
    [SKU]                           NVARCHAR (MAX)   NOT NULL,
    [SKU_Description]               NVARCHAR (MAX)   NOT NULL,
    [Vendor_Color_ID]               DECIMAL (38, 18) NOT NULL,
    [Vendor_Color]                  NVARCHAR (MAX)   NOT NULL,
    [Vendor_Color_Hex_Code]         NVARCHAR (MAX)   NOT NULL,
    [Vendor_Finish_ID]              DECIMAL (38, 18) NOT NULL,
    [Vendor_Finish]                 NVARCHAR (MAX)   NOT NULL,
    [Configuration_ID]              DECIMAL (38, 18) NOT NULL,
    [Configuration]                 NVARCHAR (MAX)   NOT NULL,
    [Display_Configuration]         NVARCHAR (MAX)   NOT NULL,
    [Size_ID]                       DECIMAL (38, 18) NOT NULL,
    [Size]                          NVARCHAR (MAX)   NOT NULL,
    [Original_Vendor_ID]            NVARCHAR (MAX)   NOT NULL,
    [Original_Vendor_fk]            INT              NOT NULL,
    [Collection_ID]                 DECIMAL (38, 18) NOT NULL,
    [Collection]                    NVARCHAR (MAX)   NOT NULL,
    [Group_ID]                      DECIMAL (38, 18) NOT NULL,
    [Group]                         NVARCHAR (MAX)   NOT NULL,
    [Product_ID]                    DECIMAL (38, 18) NOT NULL,
    [Product]                       NVARCHAR (MAX)   NOT NULL,
    [Reporting_Class_Code]          NVARCHAR (MAX)   NOT NULL,
    [Reporting_Class]               NVARCHAR (MAX)   NOT NULL,
    [Super_Category_ID]             DECIMAL (38, 18) NOT NULL,
    [Super_Category]                NVARCHAR (MAX)   NOT NULL,
    [Category_ID]                   DECIMAL (38, 18) NOT NULL,
    [Category]                      NVARCHAR (MAX)   NOT NULL,
    [Sub_Category_ID]               DECIMAL (38, 18) NOT NULL,
    [Sub_Category]                  NVARCHAR (MAX)   NOT NULL,
    [Current_EDLP_Price]            DECIMAL (38, 18) NOT NULL,
    [Good_Better_Best_Category]     NVARCHAR (MAX)   NOT NULL,
    [GBB_Price_Point]               NVARCHAR (MAX)   NOT NULL,
    [Motion]                        NVARCHAR (MAX)   NOT NULL,
    [Dining_Style]                  NVARCHAR (MAX)   NOT NULL,
    [Bedroom_Style]                 NVARCHAR (MAX)   NOT NULL,
    [Standalone_bed]                NVARCHAR (MAX)   NOT NULL,
    [SKU_Type]                      NVARCHAR (MAX)   NOT NULL,
    [Stocked]                       NVARCHAR (MAX)   NOT NULL,
    [Type_of_SKU_Code]              NVARCHAR (MAX)   NOT NULL,
    [Type_of_SKU]                   NVARCHAR (MAX)   NOT NULL,
    [Vendor_ID]                     NVARCHAR (MAX)   NOT NULL,
    [Vendor_fk]                     INT              NOT NULL,
    [Factory_ID]                    DECIMAL (38, 18) NOT NULL,
    [Factory_fk]                    INT              NOT NULL,
    [Special_Order_Available]       NVARCHAR (MAX)   NOT NULL,
    [Vendor_Lead_Time]              DECIMAL (38, 18) NOT NULL,
    [Product_Lead_Time]             DECIMAL (38, 18) NOT NULL,
    [Group_Active_Start]            DATETIME         NULL,
    [Group_Active_End]              DATETIME         NULL,
    [SKU_Flow_StartDate]            DATETIME         NULL,
    [SKU_Flow_EndDate]              DATETIME         NULL,
    [Stocked_at_EDC]                DECIMAL (38, 18) NOT NULL,
    [Stocked_at_WDC]                DECIMAL (38, 18) NOT NULL,
    [Stocked_at_FDC]                DECIMAL (38, 18) NOT NULL,
    [Group_Web_Status]              DECIMAL (38, 18) NOT NULL,
    [SKU_Web_Status]                DECIMAL (38, 18) NOT NULL,
    [Merchandising_Approval]        NVARCHAR (MAX)   NOT NULL,
    [Marketing_Approval]            NVARCHAR (MAX)   NOT NULL,
    [Lineup_Status_Code]            NVARCHAR (MAX)   NOT NULL,
    [Lineup_Status]                 NVARCHAR (MAX)   NOT NULL,
    [Available_to_Purchase]         NVARCHAR (MAX)   NOT NULL,
    [Ship_Length]                   DECIMAL (38, 18) NOT NULL,
    [Ship_Width]                    DECIMAL (38, 18) NOT NULL,
    [Ship_Height]                   DECIMAL (38, 18) NOT NULL,
    [Length]                        DECIMAL (38, 18) NOT NULL,
    [Width]                         DECIMAL (38, 18) NOT NULL,
    [Height]                        DECIMAL (38, 18) NOT NULL,
    [Weight]                        DECIMAL (38, 18) NOT NULL,
    [Prep_Cubes]                    DECIMAL (38, 18) NOT NULL,
    [Cubes]                         DECIMAL (38, 18) NOT NULL,
    [Prep_Flag]                     NVARCHAR (MAX)   NOT NULL,
    [Assembly_Required]             NVARCHAR (MAX)   NOT NULL,
    [Assembly_Time]                 DECIMAL (38, 18) NOT NULL,
    [Leave_in_Box]                  NVARCHAR (MAX)   NOT NULL,
    [Manufacturer_ID]               NVARCHAR (MAX)   NOT NULL,
    [UPC]                           DECIMAL (38, 18) NOT NULL,
    [HTS_Number]                    DECIMAL (38, 18) NOT NULL,
    [Original_SKU]                  NVARCHAR (MAX)   NOT NULL,
    [Representative_Item]           NVARCHAR (MAX)   NOT NULL,
    [Group_Rating_Count]            DECIMAL (38, 18) NOT NULL,
    [Product_Rating_Count]          DECIMAL (38, 18) NOT NULL,
    [Group_Star_Rating]             DECIMAL (38, 18) NOT NULL,
    [Product_Star_Rating]           DECIMAL (38, 18) NOT NULL,
    [Made_in_ID]                    DECIMAL (38, 18) NOT NULL,
    [Made_in_City]                  NVARCHAR (MAX)   NOT NULL,
    [Made_in_State]                 NVARCHAR (MAX)   NOT NULL,
    [Made_in_Country]               NVARCHAR (MAX)   NOT NULL,
    [Origin_ID]                     DECIMAL (38, 18) NOT NULL,
    [Origin_City]                   NVARCHAR (MAX)   NOT NULL,
    [Origin_State]                  NVARCHAR (MAX)   NOT NULL,
    [Origin_Country]                NVARCHAR (MAX)   NOT NULL,
    [Copy]                          NVARCHAR (MAX)   NOT NULL,
    [Web_Description]               NVARCHAR (MAX)   NOT NULL,
    [Price_Tag_Description]         NVARCHAR (MAX)   NOT NULL,
    [Primary_Common_Color]          NVARCHAR (MAX)   NOT NULL,
    [Primary_Common_Finish]         NVARCHAR (MAX)   NOT NULL,
    [Floor_Sample_Bedding]          NVARCHAR (MAX)   NOT NULL,
    [Employee_Bedding]              NVARCHAR (MAX)   NOT NULL,
    [Accessory_Story]               NVARCHAR (MAX)   NOT NULL,
    [IndirectDirect]                NVARCHAR (MAX)   NOT NULL,
    [3D_Model_Required]             NVARCHAR (MAX)   NOT NULL,
    [3D_Model]                      NVARCHAR (MAX)   NOT NULL,
    [Scene_7_Image_URL]             NVARCHAR (MAX)   NOT NULL,
    [Havertys.com_URL]              NVARCHAR (MAX)   NOT NULL,
    [Advertised_Price]              DECIMAL (38, 18) NOT NULL,
    [Supply_Chain_Analyst_fk]       INT              NOT NULL,
    [Supply_Chain_Analyst_nk]       INT              NOT NULL,
    [Supply_Chain_Analyst_FullName] VARCHAR (50)     NULL,
    [Product_Features]              VARCHAR (5000)   NULL,
    [Origin]                        VARCHAR (10)     NULL,
    [FOB_Cost]                      DECIMAL (10, 4)  NOT NULL,
    [Warehouse_Cost]                DECIMAL (10, 4)  NOT NULL,
    [HashKey]                       NVARCHAR (MAX)   NULL,
    [SourceSystem_fk]               INT              NOT NULL,
    [ETLBatchID_Insert]             INT              NOT NULL,
    [ETLBatchID_Update]             INT              NOT NULL,
    [SKU_sk_Dest]                   INT              NULL,
    [SKU_Unformatted_nk_Dest]       NVARCHAR (MAX)   NULL,
    [HashKey_Dest]                  NVARCHAR (MAX)   NULL,
    [ETLBatchID_Insert_Dest]        INT              NULL
)
WITH (DATA_COMPRESSION = PAGE);











