CREATE TABLE [Updates].[Dim_Customer_Update] (
    [Customer_Sequence_nk]          INT              NULL,
    [Customer_ID_nk]                BIGINT           NULL,
    [Sequence_Status]               NVARCHAR (MAX)   NOT NULL,
    [Bill_First_Name]               NVARCHAR (MAX)   NOT NULL,
    [Bill_Last_Name]                NVARCHAR (MAX)   NOT NULL,
    [Bill_Name_Status]              NVARCHAR (MAX)   NOT NULL,
    [Bill_Address]                  NVARCHAR (MAX)   NOT NULL,
    [Bill_City]                     NVARCHAR (MAX)   NOT NULL,
    [Bill_State]                    NVARCHAR (MAX)   NOT NULL,
    [Bill_ZIP]                      NVARCHAR (MAX)   NOT NULL,
    [Bill_ZIP4]                     NVARCHAR (MAX)   NOT NULL,
    [Bill_Latitude]                 DECIMAL (38, 18) NOT NULL,
    [Bill_Longitude]                DECIMAL (38, 18) NOT NULL,
    [Bill_Address_Status]           NVARCHAR (MAX)   NOT NULL,
    [Delivery_First_Name]           NVARCHAR (MAX)   NOT NULL,
    [Delivery_Last_Name]            NVARCHAR (MAX)   NOT NULL,
    [Delivery_Name_Status]          NVARCHAR (MAX)   NOT NULL,
    [Delivery_Address]              NVARCHAR (MAX)   NOT NULL,
    [Delivery_City]                 NVARCHAR (MAX)   NOT NULL,
    [Delivery_State]                NVARCHAR (MAX)   NOT NULL,
    [Delivery_ZIP]                  NVARCHAR (MAX)   NOT NULL,
    [Delivery_ZIP4]                 NVARCHAR (MAX)   NOT NULL,
    [Delivery_Latitude]             DECIMAL (38, 18) NOT NULL,
    [Delivery_Longitude]            DECIMAL (38, 18) NOT NULL,
    [Delivery_Address_Status]       NVARCHAR (MAX)   NOT NULL,
    [Customer_Profile_Created_Date] NVARCHAR (MAX)   NOT NULL,
    [Customer_First_Name]           NVARCHAR (MAX)   NOT NULL,
    [Customer_Last_Name]            NVARCHAR (MAX)   NOT NULL,
    [Customer_Name_Status]          NVARCHAR (MAX)   NOT NULL,
    [Customer_Address]              NVARCHAR (MAX)   NOT NULL,
    [Customer_City]                 NVARCHAR (MAX)   NOT NULL,
    [Customer_State]                NVARCHAR (MAX)   NOT NULL,
    [Customer_ZIP]                  NVARCHAR (MAX)   NOT NULL,
    [Customer_ZIP4]                 NVARCHAR (MAX)   NOT NULL,
    [Customer_Latitude]             DECIMAL (38, 18) NOT NULL,
    [Customer_Longitude]            DECIMAL (38, 18) NOT NULL,
    [Customer_Phone_Type]           NVARCHAR (MAX)   NOT NULL,
    [Customer_Phone]                NVARCHAR (MAX)   NOT NULL,
    [Customer_Phone_Extension]      NVARCHAR (MAX)   NOT NULL,
    [Customer_Phone_Status]         NVARCHAR (MAX)   NOT NULL,
    [Customer_Email]                NVARCHAR (MAX)   NOT NULL,
    [Customer_Email_Status]         NVARCHAR (MAX)   NOT NULL,
    [Customer_Created_Date]         DATETIME         NULL,
    [Customer_Status]               NVARCHAR (MAX)   NOT NULL,
    [No_Email]                      NVARCHAR (MAX)   NOT NULL,
    [Room_Plan]                     NVARCHAR (MAX)   NOT NULL,
    [Send_Advertising]              NVARCHAR (MAX)   NOT NULL,
    [Send_Catalog]                  NVARCHAR (MAX)   NOT NULL,
    [Send_News]                     NVARCHAR (MAX)   NOT NULL,
    [Send_P_Mail]                   NVARCHAR (MAX)   NOT NULL,
    [HashKey]                       NVARCHAR (MAX)   NULL,
    [SourceSystem_fk]               INT              NOT NULL,
    [ETLBatchID_Insert]             INT              NOT NULL,
    [ETLBatchID_Update]             INT              NOT NULL,
    [Customer_sk_Dest]              INT              NULL,
    [Customer_Sequence_nk_Dest]     INT              NULL,
    [Customer_ID_nk_Dest]           BIGINT           NULL,
    [HashKey_Dest]                  NVARCHAR (MAX)   NULL,
    [ETLBatchID_Insert_Dest]        INT              NULL
)
WITH (DATA_COMPRESSION = PAGE);

